name: Ncatest.cx.js

on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 5 * * *' 

jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependency
        run: |
          npm install
          npm init
          npm install got --save
          npm install tough-cookie --save
          node .\cx.js
